### ISSUE TITLE
Mlflow is exposed with basic authentication without TLS

### ISSUE THREAD

**Issue by fg91** [zenml-io/mlops-stacks#25]
The `gcp-kubeflow-kserve` stack recipe deploys the [mlflow tracking server](https://www.mlflow.org/docs/latest/tracking.html) which is exposed with a Nginx Ingress. The deployed tracking server [is configured](https://github.com/zenml-io/mlops-stacks/blob/988c536b2415491503d17e112406be3ce2fd57de/gcp-kubeflow-kserve/mlflow-module/ingress.tf#L21) to use only basic authentication (username + password) but does so over plain http without TLS encryption. This is dangerous (see [here](https://security.stackexchange.com/questions/988/is-basic-auth-secure-if-done-over-https/990#990), [here](https://en.wikipedia.org/wiki/Basic_access_authentication#Security:~:text=The)) since the credentials which are sent with every request when using basic auth are then not encrypted.

**Comment by wjayesh** [comment]
Hi @fg91! Thanks for raising concern on the security of the MLflow tracking server. Right now, the setup is very basic as you pointed out but I'm open to hearing any suggestions you have to make it better.
