### ISSUE TITLE
azueml-minimal stack produces resources to which one has no access rights to

### ISSUE THREAD

**Issue by fschlz** [zenml-io/mlops-stacks#31]
After tinkering with the `.tf` files a bit I got everything to be deployed to Azure. (I realize zenml stack recipes are in alpha, but maybe exclude them for the moment, because they do not work at all)
A cookiecutter template might be better option here to set all necessary variables right away, then just use Terraform.

In any case, the Azure ML service that is provisioned doesn't give my user viewing rights to see the jobs that run in the workspace.
Also, when you provision manually, a folder structure is setup `/Users/{username}` in the Notebooks section, that's also missing. When I try to create it myself, Azure won't let me.

**Comment by wjayesh** [comment]
Hi Francisco, thanks for reporting this problem. 
By default, the user that created the workspace should have owner rights over it and be able to perform all tasks, including watching jobs. 
- Can you please check the "Access Control (IAM)" tab in your AzureML workspace and see what users and their respective roles are present there?
- Next, can you check if the user that is listed there is the same one that you used to deploy the recipe?
