### ISSUE TITLE
GCP deployment fails if `gke-gcloud-auth-plugin` is not installed

### ISSUE THREAD

**Issue by fa9r** [zenml-io/mlops-stacks#44]
When trying to deploy `gcp-vertexai` the deployment failed when trying to create the namespace because I didn't have `gke-gcloud-auth-plugin` installed. See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke. 

After running `gcloud components install gke-gcloud-auth-plugin`, everything worked fine, so this is an easy fix. However, this should probably be mentioned as a requirement somewhere.

**Comment by wjayesh** [comment]
Nice catch, thanks! I've pushed a PR for it here: #46
