### ISSUE TITLE
"zenml stack recipe" seems to be deprecated

### ISSUE THREAD

**Issue by shelmigtwo** [zenml-io/mlops-stacks#7]
I was going through the [Registering the ZenML Stack](https://github.com/zenml-io/mlops-stacks/tree/main/vertex-ai#registering-the-zenml-stack-) portion of the Vertex AI MLOps Stack recipe, and tried to make use of `zenml stack recipe`, but it seems as though this part of the CLI is no longer available (or is not available with my version of ZenML)?
I am running ZenML in a docker container using the `zenmldocker/zenml` image.

**Comment by wjayesh** [comment]
Hi @shelmigtwo! The `zenml stack recipe` commands haven't been merged yet. They're available on a branch of the `zenml` repository: https://github.com/zenml-io/zenml/tree/misc/add-mlops-stacks.
Here's the active PR for it: https://github.com/zenml-io/zenml/pull/807

Two ways you can use it now:
- Install `zenml` from the `add-mlops-stacks` branch.
- Use `terraform init` and `terraform apply` directly inside the `vertex-ai` directory. This would still create a stack YAML configuration file that you can import as your ZenML stack.

**Comment by shelmigtwo** [comment]
@strickvl I'm running `0.12.0`

Thanks both for responding! @wjayesh alright that makes sense thank you! I'll take that route 👍

**Comment by wjayesh** [comment]
Hi @shelmigtwo! `zenml stack recipe` CLI commands are now available with the latest 0.13 release! Check out the release notes here: https://github.com/zenml-io/zenml/releases/tag/0.13.0

I'll go ahead and close this issue :)

**Comment by shelmigtwo** [comment]
@wjayesh perfect, thanks!
